name: teatone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.4.3
  
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  meta: ^1.15.0
  equatable: ^2.0.5

  path: ^1.9.0
  path_provider: ^2.1.5

  record: ^5.2.0
  audioplayers: ^6.1.0
  
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

  build_runner: ^2.4.13

  msix: ^3.16.8

flutter:
  uses-material-design: true

msix_config:
  display_name: TeaTone
  publisher_display_name: Greateapot
  identity_name: re.greateapot.TeaTone
  msix_version: 1.0.0.0
  logo_path: .\assets\logo.png
  start_menu_icon_path: .\assets\logo.png
  tile_icon_path: .\assets\logo.png
  icons_background_color: transparent
  architecture: x64
  capabilities: "microphone"
  languages: en-US
  build_windows: false